### ISSUE TITLE
Decrease commands start time

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/avalanche-cli#1174]
it seems to be 2 secs for any command (even much more certain times)

**Comment by arturrez** [comment]
I don't think this is a valid issue anymore @felipemadero 
after looking into timings with ansible gone, it works ok 
```
❯ /usr/bin/time ./bin/avalanche node status test2
-------> done [checkCluster] timestamp: 0.00006258 spent 9223372036.85477638
-------> done [GetAnsibleHostsFromInventory] timestamp: 0.00012146 spent 0.00005888
-------> done [utils.MapWithError] timestamp: 0.00013204 spent 0.00001058
-------> done [utils.MapWithError] timestamp: 0.00081183 spent 0.00067979
-------> done [GetInventoryFromAnsibleInventoryFile] timestamp: 0.00084283 spent 0.00003100
-------> done [checkHostsAreBootstrapped] timestamp: 1.23511750 spent 1.23427467
-------> done [checkHostsAreHealthy] timestamp: 1.38809317 spent 0.15297567
-------> done [RunSSHCheckAvalancheGoVersion] timestamp: 1.54052825 spent 0.15243508
-------> done [GetHostMapfromAnsibleInventory] timestamp: 1.54168192 spent 0.00115367
-------> done [printOutput] timestamp: 1.54245708 spent 0.00077517
 2.75 real         0.19 user         0.02 sys
 ```
 with time spent in http POST calls with ```
 Checking if node(s) are bootstrapped to Primary Network ...
-------> done [url.Parse] timestamp: 0.00000479 spent 0.00000462
-------> done [host.Forward] timestamp: 1.20233533 spent 1.20233054
Checking if node(s) are healthy ...
-------> done [url.Parse] timestamp: 0.00001175 spent 0.00001150
-------> done [host.Forward] timestamp: 0.15251333 spent 0.15250158
Getting avalanchego version of node(s)
-------> done [url.Parse] timestamp: 0.00000804 spent 0.00000792
-------> done [host.Forward] timestamp: 0.15101554 spent 0.15100750
```
which makes sense as first we spend time to auth and establish SSH connection and keep reusing it after it's there

**Comment by felipemadero** [comment]
solved
