### ISSUE TITLE
add automatic update of cloud security settings to the current local host IP

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/avalanche-cli#1271]
steps:
1) when creating the cluster, save the local host IP somewhere on node/cluster info
2) check on all node commands, if current local host IP != saved local host IP, start procedure to update the IP settings, by removing previous one, and adding new one

**Comment by felipemadero** [comment]
> idk if we need to remove old ip, maybe just add new ip

over time, the security group starts getting a lot of rules

**Comment by arturrez** [comment]
> steps:
> 
> 1. when creating the cluster, save the local host IP somewhere on node/cluster info
> 2. check on all node commands, if current local host IP != saved local host IP, start procedure to update the IP settings, by removing previous one, and adding new one

@felipemadero should we just provide command for the user to update his IP and just reference it in the error message when  ssh access to the instance fails

**Comment by felipemadero** [comment]
> > steps:
> > 
> > 1. when creating the cluster, save the local host IP somewhere on node/cluster info
> > 2. check on all node commands, if current local host IP != saved local host IP, start procedure to update the IP settings, by removing previous one, and adding new one
> 
> @felipemadero should we just provide command for the user to update his IP and just reference it in the error message when ssh access to the instance fails

I believe we may just start the procedure, anyway it may fail due to cloud credentials. we indeed we may ask the user to update credentials and wait for that.

**Comment by arturrez** [comment]
now we have separate `node whitelist` command with automatic user IP detection, so please consider closing this one as Done
