### ISSUE TITLE
Node error while deploying subnet locally(v1.3.5)

### ISSUE THREAD

**Issue by vismithaa** [ava-labs/avalanche-cli#1286]
![image](https://github.com/ava-labs/avalanche-cli/assets/148481442/77d4ff43-b199-4f1e-bc1b-062c18972362)
This issue was fixed in v1.3.4 but again this issue persists after the new version release.

This error occurs when i create a subnet -'gamenet' and deploy the subnet using 
```
avalanche subnet deploy gamenet
```

**Comment by felipemadero** [comment]
Hi! Could you please send us the complete i/o for the subnet create and subnet deploy commands that can be used to reproduce the issue.

**Comment by felipemadero** [comment]
Also send if possible a tar of ~/.avalanche-cli/runs/

**Comment by felipemadero** [comment]
ok please execute avalanche network clean and then try again to deploy. A new fix is on the way.
