### ISSUE TITLE
Unable to deploy subnet

### ISSUE THREAD

**Issue by DeeKay02** [ava-labs/avalanche-cli#1337]
I keep getting this error when I try to deploy subnet in local machine
![image](https://github.com/ava-labs/avalanche-cli/assets/48171972/30698770-f585-4890-888c-fbdf7ac9f86f)

**Comment by felipemadero** [comment]
please try `avalanche network clean` and then try again. There was a snapshot update. Next release
will completelly fix the issue.

**Comment by DeeKay02** [comment]
Tried it. Still not working
![image](https://github.com/ava-labs/avalanche-cli/assets/48171972/2dc1b4cc-30ac-49ec-a5a8-1c04397a0fe2)

**Comment by Ryab26** [comment]
Hello @DeeKay02 i will suggest you contact support like i did  a couple of days ago and got support after i opened a ticket. So i will suggest you do the same so you can talk to a [Avax live support agent](https://desks.live/avax) on the general chain link for definite answers.
You can use the  ticket ID DR3486 as well for a faster response.

**Comment by felipemadero** [comment]
I believe you passed image related to fuji deploys, but this issue is for local deploys. `network clean` was given to fix the local deploy issue.

**Comment by felipemadero** [comment]
will close this, and continue with https://github.com/ava-labs/avalanche-cli/issues/1358
