### ISSUE TITLE
Error in deploying subnet on Fuji

### ISSUE THREAD

**Issue by DeeKay02** [ava-labs/avalanche-cli#1338]
Facing error while deploying subnet in fuji. Even though I sent test AVAX tokens to the key, still showing no funds
![image](https://github.com/ava-labs/avalanche-cli/assets/48171972/e36ce3c7-2347-48b8-b212-e2521a17e26c)

**Comment by felipemadero** [comment]
could you please include an output of `avalanche key list --fuji` ?
also, pls can you include the output as ascii text in the response, not only the image

**Comment by DeeKay02** [comment]
thehypnotist@LAPTOP-BA1NH6R3:~$ avalanche key list --fuji                                                                                                                                                          +--------+------+-------------------------------+-----------------------------------------------+-------------+---------+                                                                                          |  KIND  | NAME |             CHAIN             |                    ADDRESS                    |   BALANCE   | NETWORK |                                                                                          +--------+------+-------------------------------+-----------------------------------------------+-------------+---------+                                                                                          | stored | p    | C-Chain (Ethereum hex format) | 0x74D711cA8306Ef29CFbA71cF7D3ebe98045eCDaa    | 0.210000000 | Fuji    |                                                                                          +        +      +-------------------------------+-----------------------------------------------+-------------+---------+                                                                                          |        |      | P-Chain (Bech32 format)       | P-fuji1vvgny28fttztq27fjvy7l9jtnjtdlkdwx55efv |           0 | Fuji    |                                                                                          +--------+------+-------------------------------+-----------------------------------------------+-------------+---------+         
![image](https://github.com/ava-labs/avalanche-cli/assets/48171972/4e37b084-9017-48b7-98dc-4f0dfe0ec5e0)

**Comment by felipemadero** [comment]
ok would like first 
1) to try to understand something: in the first example you were using a key named `mytestkey` but on the key list it is shown you have a key named `p`. Maybe did you remove the previous one?
in second place, I can see that for key named `p` you have funds on C-Chain, 0.21, but for CLI you need funds on P-Chain. For that, you should do a cross chain transfer between C and P in the avax wallet.

**Comment by DeeKay02** [comment]
@felipemadero Sorry yeah I deleted and changed the wallet.
![image](https://github.com/ava-labs/avalanche-cli/assets/48171972/c47e6814-e92a-4de5-8c2c-1c8562018533)
Still not working

**Comment by felipemadero** [comment]
still seeing the insufficient funds message?

**Comment by DeeKay02** [comment]
Yes I'm still receiving this error.
