### ISSUE TITLE
Completion: check for `compdef`'s existence

### ISSUE THREAD

**Issue by hsk81** [ava-labs/avalanche-cli#1357]
In `.local/share/bash-completion/completions/avalanche.sh` check for the existence of `compdef`, since otherwise every time a non-zsh shell is launched an error is thrown:

```sh
if command -v compdef &> /dev/null
then
    compdef _avalanche avalanche 
fi
```

**Comment by arturrez** [comment]
this is caused by https://github.com/spf13/cobra/issues/1529
