### ISSUE TITLE
Unable to deploy subnet in Local Network

### ISSUE THREAD

**Issue by DeeKay02** [ava-labs/avalanche-cli#1358]
Describe the bug
Unable to deploy subnet in Local Network. Been getting this "node stopped unexpectedly" for weeks.

To Reproduce
Just create a subnet and deploy in local network using Avalanche CLI

Expected behavior
Subnet be deployed and run smoothly.

Screenshots
![image](https://github.com/ava-labs/avalanche-cli/assets/48171972/77dbfb4a-18c2-4588-88b5-3cc2d3e6e45b)

Operating System
WSL

**Comment by felipemadero** [comment]
Could you please
1) update to latest CLI v1.3.6 (verify that with --version flag)
2) execute `network clean`
3) try again
If continue having issues, please provide us the compressed contents of `~/.avalanche-cli/runs`

**Comment by DeeKay02** [comment]
I already updated it previously. Still not working
![image](https://github.com/ava-labs/avalanche-cli/assets/48171972/4ab9f980-b0b3-4c32-ab83-90307a4631da)

**Comment by felipemadero** [comment]
Could you provide us the compressed contents of ~/.avalanche-cli/runs
