### ISSUE TITLE
Add flags to subnet join

### ISSUE THREAD

**Issue by dasconnor** [ava-labs/avalanche-cli#136]
We should be able to run these commands in manual and automatic mode without any prompts. We need to add the flags to do so. We definitely need a `--fuji` and `--mainnet`. Then if the user provides either `print` or (`--plugin-dir` AND `avalanchego-config`) we skip the confirmations.

**Comment by holisticode** [comment]
For this to work we also need the flags `--skip-whitelist-check` and `--force-write ` (the former for both situations described above, the latter only for the second, to edit the file)
