### ISSUE TITLE
Support http-allowed-hosts

### ISSUE THREAD

**Issue by hiepmai-crypto** [ava-labs/avalanche-cli#1536]
I was following [Accessing your local subnet remotely](https://github.com/ava-labs/avalanche-cli?tab=readme-ov-file#accessing-your-local-subnet-remotely) section to host the local network and also provide the RPC for other services.
However, the query kept returning `invalid host specified` even though I tried adding `http-allowed-hosts`. 
I'm wondering if `http-allowed-hosts` is supported? Thanks

**Comment by smondet** [comment]
Just mentioning that (at least outside of browsers?) this problem can be bypassed on the client side:

With `curl` just add the header: `--header 'Host: localhost'`

With `ethers.js`:

```js
var req = new ethers.FetchRequest( 'http://example.com/prefix' );
req.setHeader("Host", "localhost");
var provider = new ethers.JsonRpcProvider(req);
```

Cf. also [avalanchego#2200](https://github.com/ava-labs/avalanchego/issues/2200)
