### ISSUE TITLE
tls: failed to verify certificate: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by hiepmai-crypto** [ava-labs/avalanche-cli#1537]
When I run the cli using container image as `docker run --rm --name local-test -p 8000:9650 avaplatform/avalanche-cli:v1.4.0 network start`, it keeps having this error
```
Backend controller started, pid: 14, output at: /root/.avalanche-cli/runs/server_20240306_083949/avalanche-cli-backend.log
Error: failed setting up local environment: failed doing request to https://api.github.com/repos/ava-labs/avalanchego/releases/latest: 
Get "https://api.github.com/repos/ava-labs/avalanchego/releases/latest": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

My temporary solution to fix it is adding `RUN apt-get update && apt-get install -y ca-certificates` before the [ENTRYPOINT](https://github.com/ava-labs/avalanche-cli/blob/main/Dockerfile#L20). Is there any permanent fix? Thanks

**Comment by arturrez** [comment]
thank you for reporting this.
Yes we should add ca-certificates to the dockerfile.
