### ISSUE TITLE
Is Parallel SSH not working

### ISSUE THREAD

**Issue by sukantoraymond** [ava-labs/avalanche-cli#1623]
AVL-7H2W7V:avalanche-cli raymondsukanto$ ./bin/avalanche node ssh wizNodes6 pgrep avalanchego --parallel=true
Error: failed to ssh node(s) map[aws_node_i-0eca94a11bd7daff7:exit status 1]

should be
AVL-7H2W7V:avalanche-cli raymondsukanto$ ./bin/avalanche node ssh i-0e062ea96ce54a8dd pgrep avalanchego
  Node i-0e062ea96ce54a8dd (NodeID-DE8skjJuc2XEHwfYnUWiY9Lb47RJHAeJh) 54.225.179.150 [Validator]
6571
AVL-7H2W7V:avalanche-cli raymondsukanto$ ./bin/avalanche node ssh wizNodes6 pgrep avalanchego
  Node i-0eca94a11bd7daff7 (----------------------------------------) 23.23.228.80 [Monitor]
  Node i-00ee58a4f7add26ae (NodeID-5jG5CCQjygp4yd24gTvikVaSVe727kAHp) 44.195.111.152 [Validator]
6574
  Node i-0e062ea96ce54a8dd (NodeID-DE8skjJuc2XEHwfYnUWiY9Lb47RJHAeJh) 54.225.179.150 [Validator]
6571
Error: failed to ssh node(s) map[aws_node_i-0eca94a11bd7daff7:exit status 1]

**Comment by arturrez** [comment]
seems to be working 
```
./bin/avalanche node ssh loki0 --parallel=true  w
[aws_node_i-0484cbf3059b11237]  00:31:34 up 3 days,  4:00,  1 user,  load average: 0.05, 0.04, 0.01
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
ubuntu   pts/0    96.48.239.17     22:32    1:58m  0.03s  0.03s -bash

[aws_node_i-02f07bb2aa2503aa1]  00:31:34 up 3 days,  4:00,  1 user,  load average: 0.00, 0.00, 0.00
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
ubuntu   pts/0    96.48.239.17     22:47    1:41m  0.04s  0.01s sshd: ubuntu [priv]                                                                                                                                          

[aws_node_i-05100690dc0f77ada]  00:31:34 up 3 days,  4:00,  0 users,  load average: 0.00, 0.01, 0.00
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
```

I guess `--parallel=true` gets applied to `pgrep`
