### ISSUE TITLE
Subnet Create Allowlist Precompiles do not ask for manager addresses

### ISSUE THREAD

**Issue by martineckardt** [ava-labs/avalanche-cli#1696]
When creating a subnet config with `avalanche subnet create` and configuring custom precompiles it only asks for admin and enabled addresses. The manager addresses that were [recently introduced](https://github.com/ava-labs/subnet-evm/pull/801) are skipped.

```
? Configure contract deployment admin allow list: 
  ▸ Add
    Delete
    Preview
    More Info
↓   Done
```

```
Configure contract deployment enabled addresses list: 
  ▸ Add
    Delete
    Preview
    More Info
↓   Done

```

**Comment by felipemadero** [comment]
Closed by https://github.com/ava-labs/avalanche-cli/pull/1749
