### ISSUE TITLE
address comments on build from source

### ISSUE THREAD

**Issue by sukantoraymond** [ava-labs/avalanche-cli#1718]

**Comment by felipemadero** [comment]
:also, fix CI acoording to:
regarding CI, it seems CI docker image needs snap installation
some {{if .IsE2E }} logic on pkg/ssh/shell/setupBuildEnv.sh may be needed to install snap in that case
see pkg/ssh/shell/setupNode.sh as example
also RunSSHSetupBuildEnv should pass a new IsE2E variable, similar to RunSSHSetupNode
