### ISSUE TITLE
Teleporter doesn't deploy on subnet-evm

### ISSUE THREAD

**Issue by shubhamgoyal42** [ava-labs/avalanche-cli#1773]
On running the command `avalanche teleporter deploy localnet --local` it says `Error: subnet is not configured for teleporter`. The subnet localnet'vm is a fork of subnet-evm with modified genesis. I couldn't find anywhere in the docs that says that teleporter is not supported on subnet-evm.

**Comment by felipemadero** [comment]
Currently CLI only supports deploying teleporter to subnets that where created with the teleporter option set to true. Use latest CLI release and execute `avalanche subnet create localnet --force` again, checking that teleporter and relayer are enabled. 
Then execute `avalanche subnet deploy localnet --local` to get all teleporter/relayer stuff up and ready to use.

**Comment by felipemadero** [comment]
A new issue https://github.com/ava-labs/avalanche-cli/issues/1777 is created to prepare `avalanche teleporter deploy` to work independently of the teleporter option setting.

**Comment by shubhamgoyal42** [comment]
Hi @felipemadero, I'm using avalanche-cli version 1.5.2, and creating the subnet like this:

```
avalanche subnet create localnet --teleporter --force --custom --genesis genesis.json --custom-vm-path custom_evm.bin --config .avalanche-cli.json
```

and deploying like this:
```
avalanche subnet deploy localnet -l --avalanchego-version v1.11.2 --config .avalanche-cli.json
```

are these commands correct?

**Comment by felipemadero** [comment]
yes. those are correct. are you still getting that err msg? it is unexpected with that command sequence.

on the create command, you should be asked if you want to use relayer, and then see an output like this:
```
creating custom VM subnet localnet
✔ Yes
loading stored key "cli-teleporter-deployer" for teleporter deploys
  (evm address, genesis balance) = (0x32aaa04b1C166d02b0EE152dD221367687f72108, 600000000000000000000)
using latest teleporter version (v1.0.0)
✓ Successfully created subnet configuration
```
on local deploy all should work. tell me if not, and which err msg you get
