### ISSUE TITLE
Avalanche-cli subnet describe command not working for subnets deployed on fuji network

### ISSUE THREAD

**Issue by PietroFaggion** [ava-labs/avalanche-cli#1911]
I've udpated avalanche cli to 1.6.0 and if I deploy a subnet on fuji testnet following the official guide once i come to the step where i have to retrieve different informations (blockchain id and subnet id)  through the describe command i receive the erorr:

Error: unsupported network name  

If I try to do the same command using the -g flag it works so it seems to me It's a problem with the describe command that does not recognize the network on which I've deployed the subnet. It seems like it expects, as network name, instead of 'fuji' 'Fuji Testnet'.

While I'm creating the subnet, before deploying it, the describe command works properly. Once I've deployed it I get the error above.

I've already tried on different machines (one linux and one windows) and I receive the same error everywhere!

**Comment by enkaycredain** [comment]
+1
