### ISSUE TITLE
MR #1787 -- Cannot find AMI

### ISSUE THREAD

**Issue by ismail44** [ava-labs/avalanche-cli#1924]
It seems MR #1787 broke the ` avalanche node devnet wiz` command. We are getting an error 

Error: no amazon machine image found with the description Avalanche-CLI Ubuntu 20.04 Docker

It looks like the internals are looking for an AMI owned by account 931867039610 which is not shared with our account. How can we fix this?

**Comment by arturrez** [comment]
Hello.
Thank you for reporting this to us. We are looking into this

**Comment by arturrez** [comment]
@ismail44 can you please try again. Issue should be resolved now

**Comment by billo-ro** [comment]
Looks good

**Comment by ismail44** [comment]
Looks like it's working... thanks.
