### ISSUE TITLE
[subnet create explore] Always deploy Teleporter and registry if Subnet uses token from another blockchain as native token

### ISSUE THREAD

**Issue by martineckardt** [ava-labs/avalanche-cli#1927]
When a user selects `A token from another blockchain` always deploy Teleporter & Registry:

### Current implementation
```
root@codespaces-8559b9:/workspaces/avalanche-cli# avalanche subnet create testTokenFromAnotherBlockchain
✔ Subnet-EVM
✔ Use latest release version
Chain ID: 999999

✔ A token from another blockchain

[...}

Use the arrow keys to navigate: ↓ ↑ → ← 
? Do you want to connect your blockchain with other blockchains or C-Chain? (Deploy Teleporter and Registry): 
  ▸ Yes, I want my blockchain to be able to interoperate with other blockchains and the C-Chain
    No, I want to run my blockchain isolated
    Explain the difference
```

### Requested Change
Skip question if `A token from another blockchain` is selected:

<img width="550" alt="image" src="https://github.com/ava-labs/avalanche-cli/assets/10773395/b9f6c419-345c-4501-ae69-225221925ac7">

**Comment by felipemadero** [comment]
Addressed on https://github.com/ava-labs/avalanche-cli/commit/41776a0e514995d661cd85674477290946d99c16
