### ISSUE TITLE
Add note to subnet describe that Allowlist is not being updated 

### ISSUE THREAD

**Issue by siljapetasch** [ava-labs/avalanche-cli#2022]
**Problem:**
When the txAllowlist is modified through the precompile, the current status of the allowlist is not visible in `avalanche subnet describe mysubnet`.

**Possible solutions:**
Add a note  under the precompile section of `avalanche subnet describe mysubnet` that the allowlist is not being updated if you make adjustments via the precompile. Let them know to use `function readAllowList(address)` instead.

**Comment by felipemadero** [comment]
Closed by https://github.com/ava-labs/avalanche-cli/pull/2043
