### ISSUE TITLE
Teleporter Renaming

### ISSUE THREAD

**Issue by martineckardt** [ava-labs/avalanche-cli#2054]
Teleporter is getting renamed to Avalanche Interchain Messaging. Therefore, I propose to reorganize the command tree:

Since the new names are pretty long, I recommend offering the full name and a shorthand alias (e.g. `icm` and `interchain-messaging`). 

- `avalanche`
  - `icm` / `interchain-messaging`
    - `deploy`
    - `relayer`
      - `start`
      - `stop`
      - `logs`
    - `track` (prev. msg)
  - `ictt` / `interchain-token-transfer`
    - `deploy`

**Comment by felipemadero** [comment]
we already have interchain command group, with subcmd tokenTransferrer, why not

```
- `avalanche`
  - `icm` / `interchain messaging`
    - `deploy`
    - `track` (prev. msg)
  - `ictt` / `interchain tokenTransferrer`
    - `deploy`
  - `interchain relayer`
    - `start`
    - `stop`
    - `logs`
```
