### ISSUE TITLE
Please update avalanchego to version 1.11.10, coreth to version 0.13.7, subnet-evm to version 0.6.8 and anr to version 1.8.2

### ISSUE THREAD

**Issue by vtamara** [ava-labs/avalanche-cli#2077]
Today when I run:
```
curl --location --request POST 'https://api.avax.network:443/ext/info' \--header 'Content-Type: application/json' \--data-raw '{"jsonrpc":"2.0","id" :1,"method" :"info.getNodeVersion"}'
```

I see:
```
{"jsonrpc":"2.0","result":{"version":"avalanchego/1.11.10","databaseVersion":"v1.4.5","rpcProtocolVersion":"36","gitCommit":"532a1a7fd27eb284c29259b48bfa11e3770640d7","vmVersions":{"avm":"v1.11.10","evm":"v0.13.7","platform":"v1.11.10"}},"id":1}
```

So mainnet is running avalanchego 1.11.10, however `avalanche-cli` still uses avalanchego 1.11.8 that has a different gRPC version according to https://github.com/ava-labs/avalanchego/blob/master/version/compatibility.json

avalanchego 1.11.10 is used also by the other tools mentioned.

In my case I'm porting the Avalanche fundamental tools to OpenBSD/adJ and I already ported and tested the most recent version of the mentioned tools.  I would prefer to port and test an updated avalanche-cli  (instead of porting other old avalanchego, coreth, subnet-evm and anr. Please check  https://www.pasosdejesus.org/avalanche-adJ/ ).

**Comment by felipemadero** [comment]
Hi! CLI uses latest avago + subnet-evm for deployed local networks, or deploys in general. So, a curl based check should
also indicate 1.11.10 on local. Anyway, the go.mod dependencies are a bit old, To be updated on https://github.com/ava-labs/avalanche-cli/pull/2073
