### ISSUE TITLE
Failed to setup docker image on local

### ISSUE THREAD

**Issue by ManojJiSharma** [ava-labs/avalanche-cli#2094]
I'm trying to do local avalanche-cli docker setup:
Here is the error which am getting while running the subnet deploy command

> `^D`
![Screenshot from 2024-08-27 14-46-14](https://github.com/user-attachments/assets/e0703e24-1fc3-426f-a20c-3f782366ce03)

```
docker pull avaplatform/avalanche-cli
docker run avaplatform/avalanche-cli:latest subnet create local --evm --evm-chain-id 676767 --evm-defaults --evm-token SUB
docker run avaplatform/avalanche-cli:latest subnet deploy local --local

```

**Comment by ManojJiSharma** [comment]
While doing with local building it works
./bin/avalanche subnet deploy local --local

**Comment by felipemadero** [comment]
the docker run commands are each of one creating a different container. the configuration created with `subnet create` is persisted inside the first container and is not available in the second container. 

a viable solution is to mount on docker a volume to persist CLI data, eg of mounting a localhost directory
MY_LOCAL_CLI_DIR:

```
docker pull avaplatform/avalanche-cli
docker run -v MY_LOCAL_CLI_DIR:/root/.avalanche-cli/ avaplatform/avalanche-cli:latest subnet create local --evm --evm-chain-id 676767 --evm-defaults --evm-token SUB
docker run -v MY_LOCAL_CLI_DIR:/root/.avalanche-cli/  avaplatform/avalanche-cli:latest subnet deploy local --local
```

**Comment by ManojJiSharma** [comment]
@felipemadero thanks, it works for me, do it also going to work with CI. with 
```-v MY_LOCAL_CLI_DIR:/root/.avalanche-cli/```

**Comment by felipemadero** [comment]
Glad to hear that. Yes, this should also work on CI.

**Comment by ManojJiSharma** [comment]
@felipemadero Thanks

**Comment by ManojJiSharma** [comment]
@felipemadero Can you let me know how I configure avalanche cil so it will expose same main account always?
