### ISSUE TITLE
Upgrade to geth v1.10.23

### ISSUE THREAD

**Issue by yulin-dong** [ava-labs/avalanche-cli#212]
~https://github.com/ethereum/go-ethereum/releases/tag/v1.10.22~
https://github.com/ethereum/go-ethereum/releases/tag/v1.10.23

**Comment by yulin-dong** [comment]
https://twitter.com/peter_szilagyi/status/1561947614471507968?s=20&t=LPDpiSVliYAKFgurSM0WBw
`Aaand our latest release is borked.  Geth 1.10.22 contains a regression that causes the trie/state to go bad. Most probably it’s one of the PRs we’ve merged towards the new storage model / online pruner. Trying to find and fix the issue.`

We should wait for v1.10.23

**Comment by holisticode** [comment]
This has already been done as part of another bump PR
