### ISSUE TITLE
Failed waiting for network to become healthy

### ISSUE THREAD

**Issue by Be-P** [ava-labs/avalanche-cli#223]
I'm following this tutorial on [Creating an EVM Subnet on a Local Network](https://docs.avax.network/subnets/create-a-local-subnet). I've tryied to run `avalanche network start --log-level="DEBUG"` but it doesn't log anymore than 
```
...Error: failed waiting for network to become healthy: rpc error: code = Unavailable desc = error reading from server: EOF
```

I'm working on a Windows WSL machine, and I've figured out that I need to limit the file descriptors to 4096 otherwise the `avalanchego ` binary would crash. I thought it could be the issue, I've tried running `avalanche network start --log-level="DEBUG" --config="$HOME/.avalanche-cli.json"` but it still fails silently.

```
❯ cat $HOME/.avalanche-cli.json
{
  "fd-limit": 4096
}
```

Could you please help me finding out a way of better debugging the above error?

**Comment by dasconnor** [comment]
Closing because of how old this is, feel free to reopen if it's still a problem
