### ISSUE TITLE
Enable `addValidator` on the same local machine where L1 is already active 

### ISSUE THREAD

**Issue by meaghanfitzgerald** [ava-labs/avalanche-cli#2377]
## Goal

Enable users to create a new local node and add it as a validator to an L1 that is already deployed and running on their local machine. 

## Details

After a successful `avalanche blockchain deploy <L1 name>` where the user chooses to deploy their initial validators on their local machine, users should be able to successfully run `avalanche blockchain addValidator` to add an additional local node from their machine to the validator set.

### `avalanche addValidator` should:

1. After asking for the network and the P-Chain signing key, ask the user if they would 
  a. create a node locally to be added in this flow
  b. like to credentials manually of a node that has already been deployed (locally or on a remote machine, it shouldn't affect this step)

If the user selects `a`, the cli should run an identical flow as `avalanche node create` guiding the user through node creation, and then continue with the remain flow for adding a validator.

### Current limitations

The CLI does not currently support adding nodes to a cluster of validators running on a local machine.

**Comment by arturrez** [comment]
![Image](https://github.com/user-attachments/assets/3b82c9a5-9fc0-4d43-bf8a-f77f7212b75e)
