### ISSUE TITLE
Validator `balance` Features

### ISSUE THREAD

**Issue by meaghanfitzgerald** [ava-labs/avalanche-cli#2411]
## Goal

Add commands for users to manage their validator's continuous fee balance using the CLI under the `avalanche validator` command suite. 

### Assumptions and Scope

1. be able to specify `balance` per L1 validator when `ConvertSubnetToL1Tx` is called in `avalanche blockchain deploy <L1>` bootstrapping `initialValidators` 
2. be able to "get current balance" of an L1 validator 
  a. given a NodeID and SubnetID
3. be able to `IncreaseBalance`, simple [P-Chain transaction](https://github.com/ava-labs/avalanchego/blob/master/vms/platformvm/txs/increase_l1_validator_balance_tx.go) that anyone can call on behalf of any validator
  a. given a NodeID and SubnetID

## Example Usage

_From the Assumptions/Scope section above:_
1. during `avalanche blockchain deploy`, prompt the user to specify an initial balance for their initial validators
2. `avalanche validator getBalance`
  a. prompt user for NodeID, SubnetID (or use flags `--node-id=` `--subnet-id=`)
  b. return validationID, SubnetID, and current remaining balance
3. `avalanche validator increaseBalance`
  a. prompt user for NodeID, SubnetID, amount to increase in AVAX units, and P-Chain txn signing key
  b. return P-Chain txn hash when successful 

## Open Questions

Which API do we call to get validationID?

**Comment by meaghanfitzgerald** [comment]
cc: @arturrez @sukantoraymond @felipemadero

**Comment by jimmy-yii** [comment]
is there a way to query/increase the balance of a validator by hand right now?

**Comment by meaghanfitzgerald** [comment]
@jimmy-yii yes, you should be able to run `avalanche validator increaseBalance` to increase the balance, and `avalanche validator getBalance` to print your validator's current balance. use the flag `--validationID=<your-val-id>` with either command to get the balance of any active validator.
