### ISSUE TITLE
[Bug]: Error: invalid version string: validator-manager-v1.0.0

### ISSUE THREAD

**Issue by jimmy-yii** [ava-labs/avalanche-cli#2447]
**Describe the bug**

When try to create new L1 using CLI, it shows `Error: invalid version string: validator-manager-v1.0.0`

**To Reproduce**

```
avalanche blockchain create xxx
```

**Expected behavior**

Can create a chain

**Operating System**

```
avalanche version 1.8.1
```

**Comment by zzh156** [comment]
I meet the same problem

**Comment by felipemadero** [comment]
Thanks for the feedback. A fix is on the way.

**Comment by felipemadero** [comment]
https://github.com/ava-labs/avalanche-cli/pull/2448 fixes the issue. Release https://github.com/ava-labs/avalanche-cli/releases/tag/v1.8.2 contains the fix. You can update with `curl -sSfL https://raw.githubusercontent.com/ava-labs/avalanche-cli/main/scripts/install.sh | sh -s`
