### ISSUE TITLE
[Bug]: fix relayer funding for local clusters on `blockchain deploy`

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/avalanche-cli#2450]
**Describe the bug**
- it is assuming a default amount for c-chain, instead should ask the user (same as asking for funding key)
- (it can continuing assuming a default amount for the l1)
- it is not verifying the c-chain key balance, but instead fails on error. it should verify the key has enough funds,
if not, either ask for a new key, for a new balance, or give a ux message istead of failling. 
- if the target key already has the amount, it should just not fund
-

**To Reproduce**
`blockchain deploy` using local clusters, give a key that contains less balance than the default

**Expected behavior**
`insufficient funds for gas` messages after deploying ICM and asking for the funding key

**Screenshots**
![2024-12-15 10 48 37](https://github.com/user-attachments/assets/e32f6745-caba-48f8-8d55-f8e728366e06)

**Logs**
If applicable, please include the relevant logs that indicate a problem.

**Operating System**
Which OS you used to reveal the bug.

**Additional context**

**Comment by Mtsurve** [comment]
Thank you for taking the note 👍
