### ISSUE TITLE
[Bug]: Encountering error while Adding the validator.

### ISSUE THREAD

**Issue by PranaviD2** [ava-labs/avalanche-cli#2460]
**Describe the bug**
 Getting error saying failure to initialize validator registration when Add Validator command is used.

![Screenshot (1627)](https://github.com/user-attachments/assets/d5dd5abb-4d31-438e-b870-a3554573d3e4)

This is the SS of avalanche.log

![WhatsApp Image 2024-12-18 at 4 21 45 PM](https://github.com/user-attachments/assets/26954fb1-ea25-4aab-9462-2183123440c5)

**Comment by felipemadero** [comment]
Hi! This issue points to a validator manager contract that was not properly initialized. So, to an issue
in the `blockchain deploy` command used to create the L1

1) can you give cmdline and the logs for the `blockchain deploy` command executed to create the L1? it is important to
check how that command finished.
Section of a typical successful output is:
```
Now calling ConvertSubnetToL1Tx...
ConvertSubnetToL1Tx fee: 0.000036992 AVAX
ConvertSubnetToL1Tx ID: 2JnBrjemjQezS4nWAa6aFzekky9tz5zc3oHe6T2NcYNKEh9STd
Waiting for L1 to be converted into sovereign blockchain ... 100% [===============]

Restarting node node1 to track subnet
Waiting for blockchain poa to be bootstrapped
Waiting for rpc http://127.0.0.1:9650/ext/bc/Un9c9cu9RJgcKRjHHd1Ru2h2yFK1D5jwBnUX1NHDDhfQ7VE8c/rpc to be available
✓ poa-local-node-etna-devnet successfully tracking poa
✓ Checking if node is healthy...
✓ Node is healthy after 0 seconds
Initializing Proof of Authority Validator Manager contract on blockchain poa ...
✓ Proof of Authority Validator Manager contract successfully initialized on blockchain poa

```

where the most important part for the current problem is the `Initializing Proof of Authority Validator Manager contract on blockchain poa ...
✓ Proof of Authority Validator Manager contract successfully initialized on blockchain poa` part

**Comment by felipemadero** [comment]
besides checking those logs, an initialization command that can be used to initialize the manager is:
```
avalanche contract initValidatorManager <blockchainName>
```

**Comment by felipemadero** [comment]
Udate: after user log checks, it is associated to https://github.com/ava-labs/avalanche-cli/issues/2484

**Comment by felipemadero** [comment]
Update: Fixed after interaction with the user. Main issue: inconsistent state in L1 after deploying the L1 on top of 
the same  already deployed L1. To be fixed by 2484 but also part of the issue fixed just by using the latest CLI
release.
