### ISSUE TITLE
[Bug]: The validators is not displayed in the AVAX Subnets site

### ISSUE THREAD

**Issue by 0xbarchitect** [ava-labs/avalanche-cli#2504]
**Describe the bug**
- I have deployed L1 to Fuji Testnet successfully, then added a validator to L1
- The validators set is shown properly in host server, calling RPC method `validators.getCurrentValidators`
- However, the validators set is not displayed in the AVAX Subnets site

**To Reproduce**
- Create a L1 using command `blockchain create`
- Deploy L1 to Fuji Testnet using command `blockchain deploy`, then select `Fuji`
- The L1 is tracked in the [Subnet site](https://subnets-test.avax.network/subnets/bPbcvzyuJtceYfqTTVuTd4VboCRaAvCaBnXdMXsFWjEu5SYR9)

- Add validator to L1 using command `blockchain addValidator` successfully.
- The validator can be retrieved in the response of calling `validators.getCurrentValidators` RPC method

**Expected behavior**
- The validators is displayed properly in the AVAX Subnets site

**Screenshots**
![Screenshot from 2024-12-24 11-58-50](https://github.com/user-attachments/assets/939a88a7-0ee9-43cf-95f8-3dfa884f65ee)

**Logs**
If applicable, please include the relevant logs that indicate a problem.

**Operating System**
- Ubuntu 22.04

**Additional context**
- SubnetEVM v0.7.0

**Comment by meaghanfitzgerald** [comment]
@ava-labs/avacloud-backend @yulin-dong

**Comment by yulin-dong** [comment]
There is a fix almost ready to go out.
