### ISSUE TITLE
Apply upgrade bytes to local deployments

### ISSUE THREAD

**Issue by dasconnor** [ava-labs/avalanche-cli#334]
Once a set of upgrade bytes has been added to a subnet config, we need to be able to apply those upgrade bytes to a locally deployed subnet. This will involve copying the upgrade bytes into the proper avalanchego directory.

We should also be careful about what happens if you apply upgrade bytes, then call `network stop` then restart the network with a different version of avalanchego. That version will also need the upgrade bytes copied, though maybe that is better solved in a follow-up ticket.

**Comment by holisticode** [comment]
I don't think different versions of avalanchego play any role here. The update.json file needs to just be placed in a well-known config location, then it will always be picked up by the booting avalanchego - whatever version (until there's no change with this).

What we need to pay attention to though is this:

> Once an upgrade has been activated (a block after the specified timestamp has been accepted), it must always be present in upgrade.json exactly as it was configured at the time of activation (otherwise the node will refuse to start).

This means that if update bytes have already been generated, if those are going to be overwritten, then the changes need to be cumulative - add-only. If we allow overwrite of files, this can quickly become very tricky. 

Cleanest would be if we already have update bytes for a given subnet, then it would be detected and _we would be switching to edit mode_ - however, not sure how easy this can be done and how well this might work.
