### ISSUE TITLE
Feature Request: VMID in subnet export

### ISSUE THREAD

**Issue by MarcusJ42** [ava-labs/avalanche-cli#385]
Include VMID in the Networks.Fuji | Mainnet key of the below command:

`avalanche subnet export "MySubnetName" --output "output.json"`

The VMID is needed when building SubnetEVM which is downstream of subnet deployment in the current toolchain due to placement of VMID generation in the deploy command. Exporting the VMID here avoids having to grep the table output by deploy easing full pipeline automation.

**Comment by dasconnor** [comment]
Closing this in favor of #357
