### ISSUE TITLE
Write a migration guide for transitioning from subnet-cli

### ISSUE THREAD

**Issue by dasconnor** [ava-labs/avalanche-cli#392]

**Comment by holisticode** [comment]
After we identified that a "migration guide" wouldn't make too much sense (migrate what? The actual artifacts are deployed subnets), we implemented this ticket by writing a first PR which can import a subnet from a public network: https://github.com/ava-labs/avalanche-cli/pull/460

**Comment by holisticode** [comment]
Can this ticket by the previous comment be considered done? Or what should we do more? @dasconnor
