### ISSUE TITLE
Generate a ton of addresses and store them internally 

### ISSUE THREAD

**Issue by holisticode** [ava-labs/avalanche-cli#398]
Generate a ton of addresses and store them internally  so if the user gives a random P chain address from web wallet it will know which one it is

**Comment by kanatliemre** [comment]
Currently the CLI seems to only recognize address at index `0` at `m/44'/9000'/0'/0/0`
Web wallet uses dynamic addresses so the address can be any index `n` at `m/44'/9000'/0'/0/n`
The CLI should derive a bunch of addresses for these `n` values and when requested to sign with a given address it should compare agains the list and use the correct index
