### ISSUE TITLE
Fix "can deploy with multiple avalanchego versions" e2e test

### ISSUE THREAD

**Issue by holisticode** [ava-labs/avalanche-cli#416]
That e2e test (in `tests/e2e/testcases/packageman/suite.go`) really is designed to work with different avalanchego versions.

However, we might need to run the test with the same version (because subsequent versions are incompatible with each other). In that case, checking if the binary exists will return true for both cases (it's the same binary), resulting in L147 to fail (currently commented out)

**Comment by dasconnor** [comment]
Done
