### ISSUE TITLE
bump versions in e2e

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/avalanche-cli#419]
-       SubnetEVMVersion      = "v0.4.3"
-       SpacesVMVersion       = "v0.0.11"
-       AvagoVersion          = "v1.9.2"

ref macos error: 

https://github.com/ava-labs/avalanche-cli/actions/runs/3440773238/jobs/5739896641

ref commit:
059dc3046cb9b4a3351abca4d691db7d01b79046

**Comment by dasconnor** [comment]
Duplicate
