### ISSUE TITLE
Fix E2E Suite

### ISSUE THREAD

**Issue by dasconnor** [ava-labs/avalanche-cli#420]
We want to get all our tests running on recent versions.

**Comment by holisticode** [comment]
`tests/e2e/testcases/packageman/suite.go` also has a FIXME: 


If we have to use twice the same version (because they are incompatible between each other), then we can't use the same Exists check for the same version (find the FIXME in the code)

**Comment by felipemadero** [comment]
strongly related to https://github.com/ava-labs/avalanche-cli/issues/419 https://github.com/ava-labs/avalanche-cli/issues/418

**Comment by felipemadero** [comment]
Is E3E suite is more advanced than E2E one? :-P
