### ISSUE TITLE
Managing Subnets on local/private networks not managed by avalanche-network-runner

### ISSUE THREAD

**Issue by Nuttymoon** [ava-labs/avalanche-cli#462]
Hi,

I am running local networks bootstrapped using the [ansible-avalanche-collection](https://github.com/AshAvalanche/ansible-avalanche-collection) (on LXD containers).

Is there a way to configure the Avalanche CLI to target my custom local network? (I did not find any documentation that tells me that it is possible)

This could also be used to manage Subnets on any private Avalanche network.

**Comment by dasconnor** [comment]
We do actually have a little bit of support for this, but it's hacky. You effectively need to do everything for Testnet. Like `avalanche subnet deploy --testnet <subnetName>`. I don't think we're planning to add first class support for this anytime soon though, we're deeply embedded with the network runner, so it'd be a big lift to make that functionality more generic.
