### ISSUE TITLE
Remove the "vm binary already exists, invariant broken" problem

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/avalanche-cli#587]

**Comment by aaronbuchwald** [comment]
Output for context:
```
✔ Local Network
Deploying [lol] to Local Network
Backend controller started, pid: 29043, output at: /Users/aaronbuchwald/.avalanche-cli/runs/server_20230207_213343/avalanche-cli-backend
No local network running
Error: vm binary already exists, invariant broken
```

This seems to happen after playing around with deleting/stopping subnets/networks. When I went off the happy path of the tutorials, this seemed to happen pretty quickly, but I don't have exact steps to reproduce unfortunately.

**Comment by dasconnor** [comment]
I'm going to attempt to fix this by removing the plugin binary if a deploy fails.
