### ISSUE TITLE
The local subnet configuration was not saved after restarting

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanche-cli#592]
I created a new subnet locally. Next time I restart the computer and start the node, I find that the port number is different after the subnet is started, which makes the wallet of the subnet I connect to be disconnected. Do I have to reproduce the configuration every time?

**Comment by felipemadero** [comment]
Hi! You should save the local network to disk before restart, with `avalanche network stop` then start it with `avalanche network start`

**Comment by BigOceanGG** [comment]
@felipemadero thanks

**Comment by forbesus** [comment]
avalanche network stop
```Error: failed to stop network:
failed to stop node NodeID-7Xhw2mDxuDS44j42TCB6U5579esbSt3Lg: Get "http://127.0.0.1:9650/ext/metrics": dial tcp 127.0.0.1:9650: connect: connection refused
failed to stop node NodeID-MFrZFVCXPv5iCn6M9K6XduxGTYp891xXZ: Get "http://127.0.0.1:9652/ext/metrics": dial tcp 127.0.0.1:9652: connect: connection refused```
I am getting this error when I am stopping network
