### ISSUE TITLE
Does the local network have to start at least five nodes?

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanche-cli#594]
Does the local network have to start at least five nodes? Can I only start the node of 9650, other nodes do not start

**Comment by felipemadero** [comment]
Local network can start with less than five nodes by using special configurations (example 1 node network, but in that case consensus needs to be deactivated).

**Comment by BigOceanGG** [comment]
@felipemadero thanks

**Comment by BigOceanGG** [comment]
@felipemadero How to deactivate consensus
