### ISSUE TITLE
C-chain to P-chain transfer failed

### ISSUE THREAD

**Issue by BigOceanGG** [ava-labs/avalanche-cli#597]
C-chain to P-chain transfer failed, but C-chain to X-chain transfer successes.
![image](https://user-images.githubusercontent.com/42688345/218047034-ecb7d833-4993-47bd-a389-58ff2b64224e.png)

**Comment by BigOceanGG** [comment]
in fuji

**Comment by dasconnor** [comment]
This is not an avalanche-cli issue, please ask on discord.
