### ISSUE TITLE
The provided API endpoint does not support platform.getSubnet function

### ISSUE THREAD

**Issue by won-js** [ava-labs/avalanche-cli#607]
When calling add validator, appiendpoint does not support platform.getSubnet, causing this error.
Error message "Error: subnet query error: failed to decode client response: the method platform.getSubnets is not available"
<img width="918" alt="api avax network" src="https://user-images.githubusercontent.com/68256369/218636237-bf7c2164-cf9a-424d-9f41-0bca71fe4869.png">
<img width="897" alt="api avax-test network" src="https://user-images.githubusercontent.com/68256369/218636285-ddf84f9b-9f5b-4779-9eb9-a220ddb7304c.png">

Is it possible to support the platform.getSubnet function?

**Comment by felipemadero** [comment]
Are you trying to get the subnets of the local network? Pls try with http://127.0.0.1:9650/ext/bc/P
