### ISSUE TITLE
RPC protocol version not found for release candidates

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/avalanche-cli#623]
From time to time, vm mark release candidates as Latest, and are not found in compatibility.json (if present). Also, older release candidates are also shown to the user when choosing version.
It may be nice for CLI to ignore release candidate esp when looking for protocol compatibility.

**Comment by dasconnor** [comment]
We addressed this on the subnet-evm side, but we can keep this in the backlog to add extra support.
