### ISSUE TITLE
Add support for custom RPC subnet deployment 

### ISSUE THREAD

**Issue by izzetemredemir** [ava-labs/avalanche-cli#637]
Currently, the avalanche-cli tool does not provide any feature for deploying custom RPC subnets. This limits the flexibility of the tool and makes it difficult for users who want to create their own custom subnets.

It would be great if the avalanche-cli tool could support custom RPC subnet deployment. This would enable users to deploy their own custom subnets, which could be used for testing purposes or for specific use cases.

The feature should allow users to specify the configuration for the custom RPC subnet, including the network ID, chain ID, genesis block parameters, and other relevant settings. Additionally, the tool should provide an easy way to connect to the custom RPC subnet using standard RPC endpoints.

This feature would greatly enhance the functionality of the avalanche-cli tool and would make it more useful for developers and other users who need to create and deploy custom subnets.

**Comment by izzetemredemir** [comment]
My local node for example : http://127.0.0.1:9650

**Comment by dasconnor** [comment]
ahh ok, you just want to be able to set a custom RPC endpoint instead of just mainnet, fuji, and local. That sounds reasonable, but will probably be awhile before we get to it. If we hear more requests for this we may prioritize.

**Comment by izzetemredemir** [comment]
Fuji rpc rate limit is very low I am blocking sometimes and also I want to use my ANR rpc endpoint.
