### ISSUE TITLE
Avalanche subnet export bug

### ISSUE THREAD

**Issue by dasconnor** [ava-labs/avalanche-cli#648]
If you export a Subnet to file and then import it, it has trouble finding the sidecar. I think this might be a bug from when we changed how Subnet files are stored.

**Comment by dasconnor** [comment]
The exported sidecar may also be missing fields?

**Comment by holisticode** [comment]
Wasn't able to reproduce this with normal operation:
* Export on local machine: `avalanche subnet export subnetName` -> generated file `subnetName_export` 
* Import on virtualbox ubuntu guest `avalanche subnet import file /path/to/subnetName_export`
* Deploy same subnet `avalanche subnet deploy subnetName`
* Succeeded
