### ISSUE TITLE
Add validator start timestamp collection may be buggy

### ISSUE THREAD

**Issue by dasconnor** [ava-labs/avalanche-cli#649]
I'm not sure if this will be reproducable, but users reported being unable to enter the date/time for starting a validator period.

**Comment by dasconnor** [comment]
It also generated this error `">> parsing time "2023-02-24 04:37" as "2006-01-02 15:04:05": cannot parse "" as ":""`

**Comment by felipemadero** [comment]
answering rn. format should be 2023-02-24 04:37:00
regarding first user comment: it's doing output prints of "When should the validator start validationg? ..." with every key press of the entry of the date + time. ... no clues

**Comment by dasconnor** [comment]
Closing because we couldn't reproduce
