### ISSUE TITLE
Upgrade apply should allow adding new upgrades even if existing ones were in the past

### ISSUE THREAD

**Issue by darioush** [ava-labs/avalanche-cli#664]
[here](https://github.com/ava-labs/avalanche-cli/blob/27a22e7da1fbb528918f74244820263ad717286e/cmd/subnetcmd/upgradecmd/validate.go#L60) we check that all the timestamps should be in the future. however it is possible to do upgrades multiple times, so when you are adding new upgrades the existing ones will be in the past and this is not an error.

**Comment by holisticode** [comment]
Closed by https://github.com/ava-labs/avalanche-cli/pull/670
