### ISSUE TITLE
Install script fails on VirtualBox Ubuntu and WSL

### ISSUE THREAD

**Issue by DjToMeK30** [ava-labs/avalanche-cli#764]
I tried running below command on VirtualBox Ubuntu/Lubuntu
`curl -sSfL https://raw.githubusercontent.com/ava-labs/avalanche-cli/main/scripts/install.sh | sh -s`

but I always get this error
```
ava-labs/avalanche-cli info checking GitHub for latest tag
ava-labs/avalanche-cli crit unable to find '' - use 'latest' or see https://github.com/ava-labs/avalanche-cli/releases for details
```

I had to download code manually and just run avalanche-cli from there

**Comment by dasconnor** [comment]
What architecture are you running this on?

**Comment by yuwiggin** [comment]
I hava the same issue.  here is my system info:
```
Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64 x86_64 GNU/Linux
```
Any suggestion?

**Comment by DjToMeK30** [comment]
Linux VirtualBox 5.19.0-38-generic 22.04.1-Ubuntux86_64 GNU/Linux

**Comment by dasconnor** [comment]
Ok, I bet this has to do with the virtual machine/wsl experience. We'll take a look at this.
