### ISSUE TITLE
Enable users to choose spec of the cloud server instance

### ISSUE THREAD

**Issue by sukantoraymond** [ava-labs/avalanche-cli#869]
We currently default to the minimum required spec of the node defined in [AvalancheGo](https://github.com/ava-labs/avalanchego) (e.g. c5.2xlarge), but we should enable users to choose which spec they want. A nice feature to have would be to display the cost.

Need to do it for GCP too https://github.com/ava-labs/avalanche-cli/pull/1047/#discussion_r1370302273

**Comment by dasconnor** [comment]
Provide a default option and an `Other` option. If `Other`, then the user needs to enter the instance type.
