### ISSUE TITLE
Upgrade/downgrade avalanchego on node

### ISSUE THREAD

**Issue by felipemadero** [ava-labs/avalanche-cli#970]
Just used it and there is inconsistency between latest subnet-evm and latest avalanchego. We should give the user the option to downgrade/upgrade avalanchego as convenient on node sync

**Comment by martineckardt** [comment]
We’ve got a few reports from academy users about this. This occurs when a new avalancheGo version with a VM interface version change is released, but an updated subnet-EVM has not been released yet. 

I think it would be most effective for Subnet-CLI not to use the latest version of AvalancheGo, but the latest version of AvalancheGo compatible with the selected Subnet-EVM version
